"""Unified prompt builders, contracts, and routing literals."""

from backend.prompts.comment_prompt import (
    COMMENT_PROMPT_REGISTRY,
    COMMENT_SYSTEM_PROMPT,
    COMMENT_USER_PROMPT,
    render_comment_prompt,
)
from backend.prompts.generate_prompt import (
    GENERATE_PROMPT_REGISTRY,
    POLISH_SYSTEM_PROMPT,
    POLISH_USER_PROMPT,
    render_generate_prompt,
)
from backend.prompts.rewrite_prompt import (
    REWRITE_SYSTEM_PROMPT,
    REWRITE_USER_PROMPT,
    render_rewrite_prompt,
)
from backend.prompts.routing_prompt import (
    CHAT_REWRITE_SWITCH_HINT_TEXT,
    DOC_CONTEXT_HINT_TEXT,
    FORCE_REWRITE_SYSTEM_PROMPT,
    JUDGE_TARGET_SYSTEM_PROMPT,
    NON_REWRITE_HINT_TEXT,
    NO_DOCUMENT_HINT_TEXT,
    REPLY_ROUTE_LITERAL,
    REWRITE_INVALID_HINT_TEXT,
    REWRITE_PROMPT_RELEVANCE_SYSTEM_PROMPT,
    REWRITE_ROUTE_LITERAL,
    ROUTE_OR_REPLY_SYSTEM_PROMPT,
    build_rewrite_target_selection_bundle,
    parse_rewrite_target_selection,
    render_rewrite_relevance_prompt,
    render_route_or_reply_prompt,
)
from backend.prompts.types import (
    CommentPromptInput,
    GeneratePromptInput,
    RenderedPrompt,
    RewriteAssistantCandidate,
    RewriteHistoryMessage,
    RewritePromptInput,
    RewriteRelevancePromptInput,
    RewriteStateSnapshot,
    RewriteTargetSelectionBundle,
    RewriteTargetSelectionPromptInput,
    RouteHistoryMessage,
    RouteOrReplyPromptInput,
)

__all__ = [
    "CHAT_REWRITE_SWITCH_HINT_TEXT",
    "COMMENT_PROMPT_REGISTRY",
    "COMMENT_SYSTEM_PROMPT",
    "COMMENT_USER_PROMPT",
    "CommentPromptInput",
    "DOC_CONTEXT_HINT_TEXT",
    "FORCE_REWRITE_SYSTEM_PROMPT",
    "GENERATE_PROMPT_REGISTRY",
    "GeneratePromptInput",
    "JUDGE_TARGET_SYSTEM_PROMPT",
    "NON_REWRITE_HINT_TEXT",
    "NO_DOCUMENT_HINT_TEXT",
    "POLISH_SYSTEM_PROMPT",
    "POLISH_USER_PROMPT",
    "REPLY_ROUTE_LITERAL",
    "REWRITE_INVALID_HINT_TEXT",
    "REWRITE_PROMPT_RELEVANCE_SYSTEM_PROMPT",
    "REWRITE_ROUTE_LITERAL",
    "REWRITE_SYSTEM_PROMPT",
    "REWRITE_USER_PROMPT",
    "ROUTE_OR_REPLY_SYSTEM_PROMPT",
    "RenderedPrompt",
    "RewriteAssistantCandidate",
    "RewriteHistoryMessage",
    "RewritePromptInput",
    "RewriteRelevancePromptInput",
    "RewriteStateSnapshot",
    "RewriteTargetSelectionBundle",
    "RewriteTargetSelectionPromptInput",
    "RouteHistoryMessage",
    "RouteOrReplyPromptInput",
    "build_rewrite_target_selection_bundle",
    "parse_rewrite_target_selection",
    "render_comment_prompt",
    "render_generate_prompt",
    "render_rewrite_prompt",
    "render_rewrite_relevance_prompt",
    "render_route_or_reply_prompt",
]
